%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!          for Kalibr
#--------------------------------------------------------------------------------------------

# Camera calibration and distortion parameters (OpenCV) 
Camera.fx: 698.939
Camera.fy: 698.939
Camera.cx: 641.868
Camera.cy: 385.788

Camera.k1: -0.171466
Camera.k2: 0.0246144
Camera.p1: 0
Camera.p2: 0
Camera.width: 1280
Camera.height: 635

# Camera frames per second 
Camera.fps: 30

# stereo baseline times fx
Camera.bf: 83.87268

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.  (35
ThDepth: 160

#--------------------------------------------------------------------------------------------
# Stereo Rectification. Only if you need to pre-rectify the images.
# Camera.fx, .fy, etc must be the same as in LEFT.P
#--------------------------------------------------------------------------------------------

LEFT.height: 720
LEFT.width: 1280
LEFT.D: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [-0.171466, 0.0246144, 0, 0, 0]
LEFT.K: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [698.939, 0.0, 641.868, 0.0,698.939, 385.788, 0.0, 0.0, 1.0]
LEFT.R:  !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [0.9999120112182903, -0.0009509377973056863, 0.01323123345343895, 0.0009202958475869761, 0.9999968812011277, 0.002321775951843023, -0.01323340005239246, -0.002309395012399961, 0.9999097678379434]
LEFT.P:  !!opencv-matrix
   rows: 3
   cols: 4
   dt: d
   data: [573.7244704595107, 0, 645.7851181030273, 0, 0, 573.7244704595107, 394.1244983673096, 0, 0, 0, 1, 0]

RIGHT.height: 720
RIGHT.width: 1280
RIGHT.D: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [-0.172719, 0.0249559, 0, 0, 0]
RIGHT.K: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [701.05, 0.0, 657.224, 0.0, 701.05, 378.886, 0.0, 0.0, 1.0]
RIGHT.R:  !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [1, 7.330189244220825e-16, -1.081600087271539e-14, -7.646944212794553e-16, 0.9999973189103905, -0.002315636420256906, 1.081339878750143e-14, 0.002315636420256907, 0.9999973189103905]
RIGHT.P:  !!opencv-matrix
   rows: 3
   cols: 4
   dt: d
   data: [573.7244704595107, 0, 645.7851181030273, -68.84693645514129, 0, 573.7244704595107, 394.1244983673096, 0, 0, 0, 1, 0]



#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image  1200
ORBextractor.nFeatures: 1200

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 0.9
Viewer.PointSize:2
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500
